Algoritmo "exemplo_PARA"
// Desenvolver um programa que apresente todos os valores numéricos inteiros
// ímpares situados na faixa de 1000 a 1500
Var
   // Seção de Declarações das variáveis
   cont:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...

   para cont de 1000 ate 1500 passo 1 faca
      se(cont%2=1) entao
         escreval(cont)
      fimse
   fimpara

Fimalgoritmo