Algoritmo "LISTA_04.3-Q05"
// Desenvolver um programa que apresente todos os números divisíveis por 5
// que sejam menores que 50.
Var
   // Seção de Declarações das variáveis
   cont:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   cont <- 5

   para cont de 5 ate 50 passo 1 faca
      se(cont % 5 = 0) entao
         escreval(cont)
      fimse
   fimpara
Fimalgoritmo