Algoritmo "LISTA_04.4-Q01"
// Fazer um algoritmo que leia o numerador e o denominador de uma fração, e
// informe como resposta o número decimal correspondente a esta fração.
Var
// Seção de Declarações das variáveis 
num:real
den:real

Inicio
// Seção de Comandos, procedimento, funções, operadores, etc... 
escreval("Informe o numerador da fração: ")
leia(num)
escreval("Informe o denominador da fração: ")
leia(den)

escreval("A parte decimal desta fração é ",((num / den))

Fimalgoritmo