Algoritmo "LISTA 0.51 - Q03 - PROG LACOS"
// Desenvolver um programa que apresente os quadrados dos números
// inteiros de 15 até 200
Var
   // Seção de Declarações das variáveis
   cont:inteiro

Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   cont <- 15

   enquanto (cont <= 200) faca
      escreval("O quadrado de", cont, " é", (cont^2))
      cont <- cont + 1
   fimenquanto

Fimalgoritmo